"""`jello shell-init zsh`: the account wrappers, rendered once and cached.

`eval "$(jello shell-init zsh)"` defines `claude`, `cc`, `codex`, and `prime-agent` (plus
`CC` and the helpers they share). The bodies are the dotfiles wrappers ported as text --
~/dotfiles/home/.aliases:13-260 and ~/dotfiles/home/.zshrc:123-502 -- so behavior can be
compared line by line. Four call targets changed, and nothing else:

  * `_agent_profiles` runs `jello profile` on PATH instead of the absolute script path;
  * `profile create` forwards its argv to `jello profile create`, which owns every
    refusal, the confirmation prompt, and the write (record decisions create-order,
    create-argv), so the wrapper keeps no prompt of its own;
  * the codex Herdr checks and the config-baseline call became one `_codex_host_guard`
    call, made only when a host defines that function; jello never defines it;
  * the two hardcoded Homebrew paths became a PATH lookup with the old absolute path as
    the fallback.

The rendered text is cached at $XDG_CACHE_HOME/jello/shell-init.zsh (else
~/.cache/jello/shell-init.zsh) and keyed by the version on its first line: a cache written
by another version is simply re-rendered over. Rendering is pure, so two calls at one
version produce identical bytes (law L6).
"""

import os
import stat
import sys
import tempfile

from . import __version__

CACHE_NAME = "shell-init.zsh"
VERSION_PREFIX = "# jello "
ZSHRC_LINE = 'command -v jello >/dev/null && eval "$(jello shell-init zsh)"'

TEMPLATE = r'''# Ported from ~/dotfiles/home/.aliases:13-260 and ~/dotfiles/home/.zshrc:123-502.
# Do not edit this text here: it is generated by `jello shell-init zsh` from jello/shell.py.

# Claude profiles share config/history in ~/.claude. Folder names under
# ~/.claude/.profiles select the account-specific Keychain namespace and usage caches.
_cprofile_valid_name() {
  case "$1" in ''|[![:alnum:]]*|*[![:alnum:]_.-]*) return 1 ;; esac
}

# One resolver decides which account a name, alias, email, or substring means, for all
# three CLIs.
_agent_profiles() { jello profile "$@"; }

# Prints "<canonical name>\t<home dir>"; the name is empty for a codex home with no label yet.
_agent_profile_resolve() { # $1 = claude|codex|prime  $2 = query
  _agent_profiles resolve --cli "$1" -- "$2"
}

# Numbered menu on stderr, choice read from stdin, same output as _agent_profile_resolve.
# Callers must check both TTYs first: the menu is unreadable in a pipe and the read would hang.
_agent_profile_pick() { # $1 = claude|codex|prime
  local cli="$1" menu reply n line
  local -a names dirs texts fields
  menu="$(_agent_profiles menu --cli "$cli")" || return 1
  # (ps:\t:) keeps empty fields, which `read` would collapse — a codex home with no label
  # yet has an empty name and would otherwise shift its dir into the name.
  for line in "${(f)menu}"; do
    fields=("${(@ps:\t:)line}")
    names+=("${fields[2]}"); dirs+=("${fields[3]}"); texts+=("${fields[4]}")
  done
  (( $#texts )) || { print -u2 "$cli: no profiles found"; return 1; }
  print -u2 -r -- "$cli: select an account"
  for n in {1..$#texts}; do print -u2 -r -- "  $n) ${texts[$n]}"; done
  print -n -u2 "choice: "
  IFS= read -r reply || { print -u2; return 1; }
  case "$reply" in ''|*[!0-9]*) print -u2 "$cli: no account selected"; return 1 ;; esac
  (( reply >= 1 && reply <= $#texts )) || { print -u2 "$cli: invalid choice: $reply"; return 1; }
  print -r -- "${names[$reply]}"$'\t'"${dirs[$reply]}"
}

_cprofile_manage() {
  local action="${1:-}" name
  [ "$#" -gt 0 ] && shift
  case "$action" in
    list)
      [ "$#" -eq 0 ] || { print -u2 "usage: claude profile list"; return 2; }
      _agent_profiles list --cli claude --usage
      ;;
    create)
      # Every refusal, the confirmation prompt, and the write belong to `jello profile
      # create`, in that order; the wrapper only forwards what the user typed. NAME is the
      # first token whatever it looks like, so it goes after `--`: that is what keeps
      # `create -bad` a bad name rather than an unknown option. No name at all is forwarded
      # as no name, and jello answers with this CLI's usage line.
      if [ "$#" -eq 0 ]; then
        _agent_profiles create --cli claude
      else
        name="$1"; shift
        _agent_profiles create --cli claude "$@" -- "$name"
      fi
      ;;
    *)
      print -u2 "usage: claude profile {list|create NAME [--email ADDR] [--yes]}"
      return 2
      ;;
  esac
}

_claude_launch_kind() {
  local x
  while [ "$#" -gt 0 ]; do
    x="$1"; shift
    case "$x" in
      --) print session; return ;;
      -h|--help|-v|--version) print plumbing; return ;;
      --model|--effort|--add-dir|--session-id|-n|--name|--resume|-r|--continue|-c|\
      --permission-mode|--allowedTools|--disallowedTools|--mcp-config|--system-prompt|\
      --append-system-prompt|--output-format|--input-format)
        shift 2>/dev/null || break
        ;;
      --*=*|-*) ;;
      auth) print bound; return ;;
      *) print session; return ;;
    esac
  done
  print session
}

_cprofile() {
  local profile= x seen_profile=0 after_dd=0 index=1
  local resume_id= expect_resume=0
  local -a args tokens
  if [ "${1:-}" = profile ]; then
    shift
    _cprofile_manage "$@"
    return
  fi
  tokens=("$@")
  while (( index <= $#tokens )); do
    x="${tokens[$index]}"; (( index++ ))
    if (( after_dd )); then
      args+=("$x")
      continue
    fi
    # A token that is a flag (or absent) is not a resume id — `--resume` alone opens the
    # picker. Ids are only captured here, before `--`, so positional args are never scanned.
    # Each `--resume` clears the previous id (below), so a later idless one wins as "no id".
    if (( expect_resume )); then
      expect_resume=0
      case "$x" in
        -*) ;;
        ''|*[!A-Za-z0-9-]*) ;;
        *) resume_id="$x" ;;
      esac
    fi
    case "$x" in
      --) after_dd=1; args+=("$x") ;;
      --profile)
        (( seen_profile )) && { print -u2 "claude: --profile specified more than once"; return 2; }
        seen_profile=1
        # A following flag (or nothing at all) is not a value: `--profile` on its own means
        # "let me choose", so the next token stays in the loop and is parsed normally.
        if (( index <= $#tokens )) && [[ "${tokens[$index]}" != -* ]]; then
          profile="${tokens[$index]}"; (( index++ ))
        fi
        ;;
      --profile=*)
        (( seen_profile )) && { print -u2 "claude: --profile specified more than once"; return 2; }
        profile="${x#*=}"; seen_profile=1
        ;;
      --resume) resume_id=; expect_resume=1; args+=("$x") ;;
      --resume=*)
        resume_id=
        case "${x#*=}" in ''|*[!A-Za-z0-9-]*) ;; *) resume_id="${x#*=}" ;; esac
        args+=("$x")
        ;;
      *) args+=("$x") ;;
    esac
  done
  # Every source below goes through the resolver, so an old name kept by a session map or a
  # running pane still reaches its renamed account, and an email or unique substring works too.
  local resolved= kind
  kind="$(_claude_launch_kind "${args[@]}")"
  if [ -n "$profile" ]; then
    resolved="$(_agent_profile_resolve claude "$profile")" || return 2
  elif (( seen_profile )); then
    # Valueless --profile: an explicit request to choose, so no other source applies.
    [ -t 0 ] && [ -t 1 ] || { print -u2 "claude: --profile requires a name"; return 2; }
    resolved="$(_agent_profile_pick claude)" || return 2
  fi
  # No flag → the per-session map written by `jello resume map-session`, since herdr's
  # restore replays a bare `claude --resume <sid>` with neither the flag nor the pane env.
  # Ground truth for that session, so it outranks the ambient env (which may belong to
  # whatever shell happened to start the herdr server). A corrupt/stale entry falls through.
  if [ -z "$resolved" ] && [ -n "$resume_id" ]; then
    local map_file="$HOME/.claude/.profiles/.session-map/$resume_id" mapped=
    if [ -f "$map_file" ] && [ ! -L "$map_file" ]; then
      IFS= read -r mapped < "$map_file" 2>/dev/null || :
      if _cprofile_valid_name "$mapped"; then
        resolved="$(_agent_profile_resolve claude "$mapped" 2>/dev/null)"
        [ -z "$resolved" ] || touch "$map_file" 2>/dev/null  # keeps the prune off a live session
      fi
    fi
  fi
  # Still nothing → inherit the spawning session's profile (agent panes/subshells carry this env).
  if [ -z "$resolved" ] && [ -n "${AGENT_PROFILE_LABEL:-}" ]; then
    resolved="$(_agent_profile_resolve claude "$AGENT_PROFILE_LABEL")" || return 2
  fi
  if [ -z "$resolved" ] && [ "$kind" = plumbing ]; then
    _claude_binary "${args[@]}"
    return
  fi
  if [ -z "$resolved" ] && [ "$kind" = bound ]; then
    [ -t 0 ] && [ -t 1 ] || {
      print -u2 "claude: auth needs --profile NAME; run 'claude profile list' to see accounts"
      return 2
    }
    resolved="$(_agent_profile_pick claude)" || return 2
  fi
  # Nothing named this account, so spend the one about to waste the most usage rather than always
  # the same one. A pick that cannot be judged is an error, never a default profile.
  local autopick=
  if [ -z "$resolved" ]; then
    resolved="$(_agent_profiles pick --cli claude)" || {
      print -u2 "claude: --profile NAME is required; run 'claude profile list' to see available profiles"
      return 2
    }
    autopick=1
  fi

  local profile_dir= fields
  fields=("${(@ps:\t:)resolved}")
  profile="${fields[1]}"; profile_dir="${fields[2]}"
  _cprofile_valid_name "$profile" || {
    print -u2 "claude: invalid profile name: $profile"
    return 2
  }
  [ -z "$autopick" ] || print -u2 "claude: using profile '$profile' (expiring usage first; --profile overrides)"

  # Every profile names its Keychain identity by path string; the path need not exist. No
  # account rides the bare default service, so no rename can silently swap one account's
  # credentials for another's.
  AGENT_PROFILE_LABEL="$profile" CLAUDE_PROFILE_DIR="$profile_dir" \
    CLAUDE_SECURESTORAGE_CONFIG_DIR="$HOME/.claude-$profile" \
    _claude_binary "${args[@]}"
}

_claude_binary() { command claude "$@"; }

claude() { _cprofile "$@"; }
cc() { claude "$@"; }

CC() { cc "$@"; }

# Codex account profiles: --profile NAME swaps CODEX_HOME (auth + sessions). The base account
# at ~/.codex is named by its profile-label file; every other account lives at ~/.codex-NAME
# The profile helpers discover this layout. Names, emails, and unique substrings all resolve
# through `jello profile` — no account is the hardcoded default. Upstream --profile (config
# overlay) is shadowed by this; use -p for the upstream flag.
# Sessions live inside the home, so the Codex picker only ever sees one account's; `codex profile
# sessions` is the listing that spans them.
_codexprofile_manage() {
  local action="${1:-}" name
  [ "$#" -gt 0 ] && shift
  case "$action" in
    list)
      [ "$#" -eq 0 ] || { print -u2 "usage: codex profile list"; return 2; }
      _agent_profiles list --cli codex --usage
      ;;
    create)
      if [ "$#" -eq 0 ]; then
        _agent_profiles create --cli codex
      else
        name="$1"; shift
        _agent_profiles create --cli codex "$@" -- "$name"
      fi
      ;;
    sessions)
      local -a opts=()
      while [ "$#" -gt 0 ]; do
        case "$1" in
          --all|--json) opts+=("$1"); shift ;;
          --limit)
            case "${2:-}" in
              ''|*[!0-9]*) print -u2 "codex: --limit needs a number"; return 2 ;;
            esac
            opts+=(--limit "$2"); shift 2
            ;;
          *)
            print -u2 "usage: codex profile sessions [--all] [--limit N] [--json]"
            return 2
            ;;
        esac
      done
      _agent_profiles sessions --cli codex "${opts[@]}"
      ;;
    *)
      print -u2 "usage: codex profile {list|create NAME [--yes]|sessions [--all] [--limit N] [--json]}"
      return 2
      ;;
  esac
}

# The subcommand is the first token that is not a global option or the value of one — `codex -C
# /tmp resume` is a resume, not a session start. Options are skipped by name because only the
# binary knows which ones take a value; an unknown flag is assumed to take none, and `--flag=x`
# never consumes the next token. `-h`/`--help`/`-V`/`--version` are reported as themselves so the
# caller can treat them like the plumbing subcommands they behave as.
_codex_subcommand() {
  local x
  while [ "$#" -gt 0 ]; do
    x="$1"; shift
    case "$x" in
      --) break ;;
      -h|--help|-V|--version) print -r -- "$x"; return ;;
      -c|--config|-i|--image|-m|--model|-p|--profile|-s|--sandbox|-a|--ask-for-approval|\
      -C|--cd|--add-dir|--enable|--disable|--remote|--remote-auth-token-env|--local-provider)
        shift 2>/dev/null || break
        ;;
      -*) ;;
      *) print -r -- "$x"; return ;;
    esac
  done
}

# The wrapper shadows the binary's own name, so the lookup has to search PATH only:
# `command -v codex` would answer with this function and the fallback could never be
# reached. `whence -p` is that PATH-only lookup.
_codex_binary() {
  local bin
  bin="$(whence -p codex 2>/dev/null)"
  command "${bin:-/opt/homebrew/bin/codex}" "$@"
}

codex() {
  if [[ "${1:-}" == "profile" ]]; then
    shift
    _codexprofile_manage "$@"
    return
  fi

  local x profile= seen_profile=0 after_dd=0 index=1
  local -a args tokens=("$@")
  while (( index <= $#tokens )); do
    x="${tokens[$index]}"; (( index++ ))
    if (( after_dd )); then
      args+=("$x")
      continue
    fi
    case "$x" in
      --) after_dd=1; args+=("$x") ;;
      --profile)
        (( seen_profile )) && { print -u2 "codex: --profile specified more than once"; return 2; }
        seen_profile=1
        # A following flag (or nothing at all) is not a value: `--profile` on its own means
        # "let me choose", so the next token stays in the loop and is parsed normally.
        if (( index <= $#tokens )) && [[ "${tokens[$index]}" != -* ]]; then
          profile="${tokens[$index]}"; (( index++ ))
        fi
        ;;
      --profile=*)
        (( seen_profile )) && { print -u2 "codex: --profile specified more than once"; return 2; }
        profile="${x#*=}"
        seen_profile=1
        ;;
      *) args+=("$x") ;;
    esac
  done

  # Which account this invocation belongs to. An explicit --profile always wins and always
  # exports the home, base included; a valueless --profile means "let me choose". Without the
  # flag a session-starting run auto-picks the account about to waste the most usage — nothing
  # silently lands on the base account any more. Account-bound subcommands never auto-pick:
  # they read or write sessions and credentials that belong to one home. Plumbing subcommands
  # keep running on the binary's own default home. A caller-set CODEX_HOME stays untouched.
  local resolved="" autopick="" subcommand=""
  subcommand="$(_codex_subcommand "${args[@]}")"
  if [[ -n "$profile" ]]; then
    resolved="$(_agent_profile_resolve codex "$profile")" || return 2
  elif (( seen_profile )); then
    [[ -t 0 && -t 1 ]] || { print -u2 "codex: --profile requires a name"; return 2; }
    resolved="$(_agent_profile_pick codex)" || return 2
  elif [[ -z "${CODEX_HOME:-}" ]]; then
    case "$subcommand" in
      --help|-h|--version|-V|mcp|app-server|completion|debug|cloud|features|apply) ;;
      login|logout|resume|fork|archive|unarchive|delete)
        [[ -t 0 && -t 1 ]] || {
          print -u2 "codex: $subcommand needs --profile NAME; run 'codex profile list' to see accounts"
          return 2
        }
        resolved="$(_agent_profile_pick codex)" || return 2
        ;;
      *)
        resolved="$(_agent_profiles pick --cli codex)" || {
          print -u2 "codex: no account could be picked; pass --profile NAME"
          return 2
        }
        autopick=1
        ;;
    esac
  fi

  if [[ -n "$resolved" ]]; then
    # (ps:\t:) keeps the empty name field a codex home with no profile-label yet produces.
    local profile_name profile_dir
    local -a fields=("${(@ps:\t:)resolved}")
    profile_name="${fields[1]}"; profile_dir="${fields[2]}"
    local -x CODEX_HOME="$profile_dir" CODEX_CONFIG_PATH="$profile_dir/config.toml"
    [[ -n "$autopick" ]] && print -u2 "codex: using profile '${profile_name:-${profile_dir:t}}' (expiring usage first; --profile overrides)"
  fi

  # Launch policy belongs to the host, not to jello: the Herdr checks and the Codex config
  # baseline the dotfiles wrapper ran here are whatever defines _codex_host_guard. jello
  # never defines it, and without it the binary runs directly. The guard classifies by the
  # scanned subcommand, not args[1], so a global option in front of it (`codex -C /tmp
  # exec …`) cannot walk past the check.
  if (( $+functions[_codex_host_guard] )); then
    _codex_host_guard "$subcommand" "${args[@]}" || return
  fi

  _codex_binary "${args[@]}"
}

_prime_profile_manage() {
  local action="${1:-}" name
  [ "$#" -gt 0 ] && shift
  case "$action" in
    list)
      [ "$#" -eq 0 ] || { print -u2 "usage: prime-agent profile list"; return 2; }
      _agent_profiles list --cli prime --usage
      ;;
    create)
      if [ "$#" -eq 0 ]; then
        _agent_profiles create --cli prime
      else
        name="$1"; shift
        _agent_profiles create --cli prime "$@" -- "$name"
      fi
      ;;
    *)
      print -u2 "usage: prime-agent profile {list|create NAME [--yes]}"
      return 2
      ;;
  esac
}

_prime_launch_kind() {
  local x index=1
  local -a tokens=("$@")
  while (( index <= $#tokens )); do
    x="${tokens[$index]}"; (( index++ ))
    case "$x" in
      --) print session; return ;;
      -h|--help|-v|--version) print plumbing; return ;;
      -c|--continue|-r|--resume|--resume=*|--fork|--fork=*) print bound; return ;;
      --mode|--cwd|--daemon-socket|--provider|--model|--api-key|--models|--thinking|\
      --session-dir|--goal|--goal-token-budget|-t|--tools|-e|--extension|--skill|\
      --prompt-template|--theme|--system-prompt|--append-system-prompt|--autonomous-gate|\
      --autonomous-gate-retries|--autonomous-gate-timeout-ms|--autonomous-max-continuations|\
      --autonomous-max-turns|--autonomous-max-tokens|--autonomous-timeout-ms)
        (( index++ ))
        ;;
      --*=*|-p|--print|--offline|--verbose|--no-session|-nt|--no-tools|-nbt|\
      --no-builtin-tools|-ne|--no-extensions|-ns|--no-skills|-np|\
      --no-prompt-templates|--no-themes|-nc|--no-context-files|--autonomous) ;;
      -*) ;;
      help|model|config|package|update) print plumbing; return ;;
      agents|list|attach|stop|rename|send|schedule|status|doctor|shutdown|session)
        print bound; return ;;
      *) print session; return ;;
    esac
  done
  print session
}

# Same PATH-only lookup as _codex_binary, for the same reason.
_prime_binary() {
  local bin
  bin="$(whence -p prime-agent 2>/dev/null)"
  command "${bin:-/opt/homebrew/bin/prime-agent}" "$@"
}

prime-agent() {
  if [[ "${1:-}" == "profile" ]]; then
    shift
    _prime_profile_manage "$@"
    return
  fi

  local x profile= provider= seen_profile=0 after_dd=0 index=1
  local -a args tokens=("$@")
  while (( index <= $#tokens )); do
    x="${tokens[$index]}"; (( index++ ))
    if (( after_dd )); then
      args+=("$x")
      continue
    fi
    case "$x" in
      --) after_dd=1; args+=("$x") ;;
      --profile)
        (( seen_profile )) && { print -u2 "prime-agent: --profile specified more than once"; return 2; }
        seen_profile=1
        if (( index <= $#tokens )) && [[ "${tokens[$index]}" != -* ]]; then
          profile="${tokens[$index]}"; (( index++ ))
        fi
        ;;
      --profile=*)
        (( seen_profile )) && { print -u2 "prime-agent: --profile specified more than once"; return 2; }
        profile="${x#*=}"; seen_profile=1
        ;;
      --provider)
        args+=("$x")
        if (( index <= $#tokens )); then
          provider="${tokens[$index]}"; args+=("$provider"); (( index++ ))
        fi
        ;;
      --provider=*) provider="${x#*=}"; args+=("$x") ;;
      *) args+=("$x") ;;
    esac
  done

  local resolved="" kind autopick=""
  kind="$(_prime_launch_kind "${args[@]}")"
  if [[ -n "$profile" ]]; then
    resolved="$(_agent_profile_resolve prime "$profile")" || return 2
  elif (( seen_profile )); then
    [[ -t 0 && -t 1 ]] || { print -u2 "prime-agent: --profile requires a name"; return 2; }
    resolved="$(_agent_profile_pick prime)" || return 2
  elif [[ -n "${PRIME_AGENT_PROFILE_LABEL:-}" ]]; then
    resolved="$(_agent_profile_resolve prime "$PRIME_AGENT_PROFILE_LABEL")" || return 2
  elif [[ -z "${PRIME_AGENT_CODING_AGENT_DIR:-}" && "$kind" == bound ]]; then
    [[ -t 0 && -t 1 ]] || {
      print -u2 "prime-agent: this command needs --profile NAME; run 'prime-agent profile list' to see accounts"
      return 2
    }
    resolved="$(_agent_profile_pick prime)" || return 2
  elif [[ -z "${PRIME_AGENT_CODING_AGENT_DIR:-}" && "$kind" == session && ( -z "$provider" || "$provider" == "openai-codex" ) ]]; then
    resolved="$(_agent_profiles pick --cli prime)" || {
      print -u2 "prime-agent: no account could be picked; pass --profile NAME"
      return 2
    }
    autopick=1
  fi

  if [[ -n "$resolved" ]]; then
    local profile_dir fields
    fields=("${(@ps:\t:)resolved}")
    profile="${fields[1]}"; profile_dir="${fields[2]}"
    _cprofile_valid_name "$profile" || { print -u2 "prime-agent: invalid profile name: $profile"; return 2; }
    local -x PRIME_AGENT_PROFILE_LABEL="$profile"
    local -x PRIME_AGENT_CODING_AGENT_DIR="$profile_dir"
    [[ -z "$autopick" ]] || print -u2 "prime-agent: using profile '$profile' (expiring usage first; --profile overrides)"
  fi

  _prime_binary "${args[@]}"
}
'''


def render_zsh(version):
    """The whole init script. Pure: same version in, same bytes out (law L6)."""
    return f"{VERSION_PREFIX}{version}\n{TEMPLATE}"


def cache_dir(home=None):
    base = os.environ.get("XDG_CACHE_HOME")
    if not base:
        base = os.path.join(os.path.expanduser("~") if home is None else home, ".cache")
    return os.path.join(base, "jello")


def cache_path(home=None):
    return os.path.join(cache_dir(home), CACHE_NAME)


def read_cache(version, home=None):
    """The cached text when its first line carries this version, else None. The only
    invalidation there is: a cache from another version is re-rendered over."""
    path = cache_path(home)
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except (OSError, UnicodeDecodeError):
        return None
    first = text.partition("\n")[0]
    return text if first == f"{VERSION_PREFIX}{version}" else None


def write_cache(text, home=None):
    """Temp file and rename, so a shell that evaluates the cache never reads half a script."""
    path = cache_path(home)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(dir=os.path.dirname(path), prefix=f".{CACHE_NAME}.")
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise
    return path


def cached_text(version, home=None):
    """The text to print: the cache when it is current, else a fresh render written over it.
    A cache that cannot be written is not an error -- the script is still printed."""
    text = read_cache(version, home)
    if text is not None:
        return text
    text = render_zsh(version)
    try:
        write_cache(text, home)
    except OSError:
        pass
    return text


def run(args):
    sys.stdout.write(cached_text(__version__))
    return 0


def register(subparsers):
    parser = subparsers.add_parser(
        "shell-init",
        help="print the shell wrappers to eval",
        description=__doc__.splitlines()[0],
    )
    parser.add_argument("shell", choices=("zsh",))
    parser.set_defaults(run=run)
    return parser
